### ISSUE TITLE
SO bad acts

### ISSUE THREAD

**Issue by amerllica** [mleister97/ant-design-react-pdf-slow#1]
Hi dear Michael, recently I banned from irregular voting. but It's weird because I see the accepted answer by you is reversed also its upvote. Do you unaccept the answer? if yes I'm ok with it but I guess the moderators did it and it is not valid.

**Comment by mleister97** [comment]
Hi, sorry for late answer

No I didn't, this was done automatically.

But I already accepted your answer again.

**Comment by amerllica** [comment]
The acceptance or the reputation or bounty is not important, it is important a moderator or SE staff reverse some actions that they are applied by a user, God damn you. we are human, all thing related to our life is important, why another human allow himself/herself to neutralize mine?

I never come back to this damn community
